### PR TITLE
Add the image_size.

### PR DESCRIPTION
**Pull request by tanminger**
Signed-off-by: Ming Tan <ming.tan@intel.com>

### CODE REVIEW

**Comment by ttzeng** [comment]
@tanminger Instead of having this article as a separate tutorial, I'd proposed to add the content to the Build from Source guide. If you are ok with it, I can edit the doc to incorporate these information.

**Comment by tanminger** [comment]
@ttzeng  Do you mean the "getting_started/build-source.rst" file?

**Comment by ttzeng** [comment]
> @ttzeng Do you mean the "getting_started/build-source.rst" file?

@tanminger Yes, I think the customization of partition size can be extended to that page. If you are ok, I plan to add your context there.

**Comment by tanminger** [comment]
@ttzeng I think the "getting_started/build-source.rst" should be simple, and let the developer can simple compile it and try. How to modify some default setting should be advanced feature.

**Comment by tanminger** [comment]
@ttzeng  Maybe you can add some content about live boot to the 'getting_started/build-source.rst'

**Pull request closed without merging**
