### PR TITLE
Add script for Debugging using gdb

### PR DESCRIPTION
**Pull request by harishkrupo**
Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Comment by harishkrupo** [comment]
@ttzeng Please review

**Comment by ttzeng** [comment]
@harishkrupo, it would be good to have introduction / overview / what problem this PR is trying to solve at the beginning of a tutorial.
In addition, 'gdb' is prerequisite, and also make sure `android_gdb.sh` script has executable permission.

**Comment by ttzeng** [comment]
@harishkrupo  @arun1778 any update on this PR? if this topic is not sufficient for a dedicate tutorial, I am thinking to create a "container" tutorial to collect all the debug tips, and move your contribution as a section of that debugging tips tutorial. How do you think?

**Comment by harishkrupo** [comment]
@ttzeng Apologies. Was stuck with something else. 
A container tutorial is a good idea and I think it is required. We have a few more debug tips and tricks that need to be copied from AIA. Listing all of them under a single heading would improve the ease of access.

**Comment by ttzeng** [comment]
@harishkrupo I've merged this PR in [this page](https://01.org/projectceladon/documentation/tutorials/software-debug-tips) to collect software debug tips. I'm closing this PR, please review/submit/add changes via future PRs to beef up that page. Thanks.

**Pull request closed without merging**
